project:
  type: website
  output-dir: docs

website:
  title: "LT2010 - Data Science for Transport and Logistics Systems - Intake 23 (University of Moratuwa)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - home.qmd
      - ia.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

