---
title: "Teaching and Learning Materials"
---

**Lecturer in charge for LT2010: Data Science for Transport and Logistics Systems (R programming section):** [Dr Thiyanga S. Talagala](https://thiyanga.netlify.app/)

These notes contain only the R Programming and Data Analysis portion of LT2010: Data Science for Transport and Logistics Systems.

I’ll be conducting four lectures in total, spread across 12 hours. They’ll be named TT-Lecture 01, TT-Lecture 02, TT-Lecture 03, and TT-Lecture 04.

## Link to the moodel

[Click here](https://online.uom.lk/login/index.php)

## Pre-requisite for TT-Lecture 01

Click [here](/week0/index.html) to view the task you need to complete before TT-Lecture 01

## TT-Lecture 1

Date: September 8, 2025

Time: 1.15pm - 4.15pm

Zoom link: available on Moodle

**Slides-TT1:**

[Click here](/week1/index.html)

**Reading and Exercises:**

[Chapter 1](https://thiyangt.github.io/rbook/intro.html)



Installing packages - in class demo

Documenting with RMarkdown - in class demo

## TT-Lecture 2

Date: September 15, 2025

Time: 1.15pm - 4.15pm


- Creating dataframes 

[Chapter 2- 2.3 and 2.4](https://thiyangt.github.io/rbook/chap2.html)

- [Introduction to tidyverse](https://thiyangt.github.io/rbook/chap7.html)

- [Data wrangling](https://thiyangt.github.io/rbook/chap8.html)

- [Data visualisation](https://thiyangt.github.io/rbook/chap9.html)

## TT-Lecture 3

## TT-Lecture 4
